#!/bin/sh
# ----------------------------------------------------------------------------
# Copyright (c) 2020, Arm Limited and affiliates.
#
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ----------------------------------------------------------------------------

# we write to a tmp file so that it is automatically deleted when
# the device is rebooted, yet persists through a simple restart.  by
# doing this, we prevent edge-core from immediately re-registering
# after the factory reset is completed.
touch /tmp/factory-reset-in-progress

# Stop and remove all existing docker containers and images
snapctl stop ${SNAP_INSTANCE_NAME}.kubelet || true
docker stop $(docker ps -a -q) || true
docker system prune --volumes -a -f || true

# clear logs
journalctl --vacuum-time=1s

# syslog made a copy of journalctl so we need to delete those too
systemctl stop syslog.socket rsyslog.service
# attempt to delete /var/log/syslog and /var/log/syslog.X.gz
rm -f /var/log/syslog*
# sometimes the rm doesn't work, so let's try to truncate to 0
find /var/log -type f -print0 | xargs -0 truncate --size=0

# delete versioned r/w data but preserve mbed credentials if they
# exist. edge-core handles the mbed credentials on factory reset and
# it has different behavior based on whether it's configured for
# dev mode or factory mode.
[ -n "${SNAP_DATA}" ] && {
	find ${SNAP_DATA} -depth \
		-not -wholename "${SNAP_DATA}" \
		-not -path "${SNAP_DATA}/userdata/mbed*" \
		-not -wholename "${SNAP_DATA}/userdata/mbed" \
		-exec rm -fd {} \;
}

# delete unversioned r/w data
[ -n "${SNAP_COMMON}" ] && rm -rf ${SNAP_COMMON}

# delete custom environment variables
snapctl unset edge-core.proxy
snapctl unset edge-core.refresh-timeout
snapctl unset edge-proxy.debug
snapctl unset edge-proxy.extern-http-proxy-uri
snapctl unset kubelet.edgenet-gateway
snapctl unset kubelet.edgenet-subnet

# it's very important for this script to return success, otherwise
# edge-core won't clean up mbed credentials
exit 0
