name: pelion-edge
base: core
version: "1.2"
summary: Pelion Edge
description: Pelion Edge
confinement: strict
grade: devel
architectures: 
  - amd64

# List of applications (commands, binaries, daemons) in the snap.
apps:
    edge-core:
      command: ./edge-core -o 8081
      plugs: [network-bind]
parts:
    edge-core:
      plugin: cmake
      source: https://github.com/ARMmbed/mbed-edge.git
      source-tag: 0.9.0
      build-packages:
        - build-essential
        - g++
        - cmake
        - git
        - libcunit1-dev
        - libc6-dev
        - libmosquitto-dev
        - mosquitto-clients
      override-pull: | 
        snapcraftctl pull
        cp ../../../mbed_cloud_dev_credentials.c config/mbed_cloud_dev_credentials.c 
      configflags:
        - -DFIRMWARE_UPDATE=OFF
        - -DDEVELOPER_MODE=ON
      override-build: |
        snapcraftctl build
        install bin/edge-core ${SNAPCRAFT_PART_INSTALL}
