unixLogSocket: /tmp/grease.socket
sysLogSocket: /run/systemd/journal/syslog
linuxKernelLog: false
httpUnixSocket: /tmp/maestroapi.sock
configDBPath: "{{SNAP_DATA}}/userdata/etc/maestroConfig.db"
imagePath: /tmp/maestro/images
scratchPath: /tmp/maestro/scratch
clientId: "{{ARCH_SERIAL_NUMBER}}"
network:
    disable: true
platform_readers:
  - platform: "fsonly"
    params:
      identityPath: "/var/snap/pelion-edge/current/userdata/edge_gw_identity/identity.json"
var_defs:
   - key: "SNAP_DATA"
     value: "/var/snap/pelion-edge/current"
   - key: "SNAP"
     value: "/snap/pelion-edge/current"
   - key: "TMP_DIR"
     value: "/tmp"
   - key: "WIGWAG_NODE_PATH"
     value: "{{SNAP}}/wigwag/devicejs-core-modules/node_modules"
   - key: "WIGWAG_DIR"
     value: "{{SNAP}}/wigwag"
   - key: "NODE_EXEC"
     value: "{{SNAP}}/wigwag/system/bin/node"
   - key: "MAESTRO_RUNNER_DIR"
     value: "{{SNAP}}/wigwag/devicejs-core-modules/maestroRunner"
   - key: "LOCAL_DEVICEDB_PORT"
     value: 9000
   - key: "LOCAL_DATABASE_STORAGE_DIRECTORY"
     value: "{{SNAP_DATA}}/userdata/etc/devicedb/db"
   - key: "RELAY_VERSIONS_FILE"
     value: "{{SNAP}}/wigwag/etc/versions.json"
   - key: "FACTORY_VERSIONS_FILE"
     value: "{{SNAP}}/wigwag/etc/versions.json"
   - key: "USER_VERSIONS_FILE"
     value: "{{SNAP}}/wigwag/etc/versions.json"
   - key: "UPGRADE_VERSIONS_FILE"
     value: "{{SNAP}}/wigwag/etc/versions.json"
gateway_capabilities:
  edge_core_socketpath: "/tmp/edge.sock"
  lwm2m_objectid: 33457
  gateway_resources:
  - name: "urn:fid:pelion.com:log:1.0.0"
    enable: true
    config_filepath: "{{SNAP_DATA}}/maestro-config.yaml"
  - name: "urn:fid:pelion.com:terminal:1.0.0"
    enable: true
    config_filepath: "{{SNAP_DATA}}/wigwag/etc/relayterm-config.json"
  - name: "urn:fid:pelion.com:kaas:1.0.0"
    enable: true
    config_filepath: "{{SNAP}}/wigwag/system/var/lib/kubelet/kubeconfig"
mdns:
  # disable: true
  static_records:
   - name: "WigWagRelay"
     service: "_wwservices._tcp"  # normally something like https or ftp
     # domain: "local"     # local is default
     interfaces: "eth0"
     not_interfaces: "Witap0"
     port: 3131
     text:
      - "wwid={{ARCH_SERIAL_NUMBER}}"
     hostname: "wigwaggateway"
   - name: "WigWagRelay_{{ARCH_SERIAL_NUMBER}}"
     service: "_wwservices._tcp"  # normally something like https or ftp
     # domain: "local"     # local is default
     interfaces: "eth0"
     not_interfaces: "Witap0"
     port: 3131
     text:
      - "wwid={{ARCH_SERIAL_NUMBER}}"
     hostname: "{{ARCH_SERIAL_NUMBER}}"
targets:
   - file: "{{SNAP_DATA}}/userdata/maestro.log"
     rotate:
         max_files: 4
         max_file_size: 10000000  # 10MB max file size
         max_total_size: 42000000
         rotate_on_start: true
     delim: "\n"
     format_time: "[%ld:%d] "
     format_level: "<%s> "
     format_tag: "{%s} "
     format_origin: "(%s) "
     filters:
       - levels: warn
         format_pre: "\u001B[33m"    # yellow
         format_post: "\u001B[39m"
       - levels: error
         format_pre: "\u001B[31m"    # red
         format_post: "\u001B[39m"
static_file_generators:
   - name: "devicedb"
     template_file: "{{SNAP}}/wigwag/etc/templates/template.devicedb.conf"
     output_file: "{{SNAP_DATA}}/wigwag/etc/devicejs/devicedb.yaml"
config_end: true
