apiVersion: v1
kind: Pod
metadata:
  name: test-pod-016c6de7e4f7000000000001001003c1
spec:
  automountServiceAccountToken: false
  containers:
  - args:
    - -c
    - echo 'hello'; sleep 6000000
    command:
    - /bin/sh
    image: alpine:3.9
    imagePullPolicy: IfNotPresent
    name: client
    resources:
      limits:
        cpu: 200m
        memory: 100Mi
      requests:
        cpu: 200m
        memory: 10Mi
    volumeMounts:
    - mountPath: /my_secret
      name: examplesecret
    - mountPath: /my_cm
      name: examplecm
  hostname: test-pod
  nodeName: 016c6de7e4f7000000000001001003c1
  volumes:
  - name: examplecm
    configMap:
      name: my-cm
  - name: examplesecret
    secret:
      secretName: my-secret