name: pelion-edge
base: core
version: "1.2"
summary: Pelion Edge
description: Pelion Edge
confinement: strict
grade: devel
architectures: 
  - amd64

# List of applications (commands, binaries, daemons) in the snap.
apps:
    edge-core:
      command: launch-edge-core.sh
      daemon: simple
      plugs: [network-bind]
    edge-core-reset-storage:
      command: launch-edge-core.sh --reset-storage
      plugs: [network-bind]
    help:
      command: cat ${SNAP}/help.md
layout:
    /var/lib/edge-core:
        bind: $SNAP_DATA/var/lib/edge-core
parts:
    edge-core:
      plugin: cmake
      source: https://github.com/ARMmbed/mbed-edge.git
      source-tag: 0.9.0
      build-packages:
        - build-essential
        - cmake
        - git
      override-pull: | 
        snapcraftctl pull
        git submodule update --init --recursive
        cp ${SNAPCRAFT_PROJECT_DIR}/mbed_cloud_dev_credentials.c config/mbed_cloud_dev_credentials.c
        cp ${SNAPCRAFT_PROJECT_DIR}/cmake/target.cmake config/target.cmake
        cp ${SNAPCRAFT_PART_SRC}/cmake/toolchains/mcc-linux-x86.cmake config/toolchain.cmake
      configflags:
        - -DCMAKE_BUILD_TYPE=Release
        - -DTRACE_LEVEL=INFO
        - -DFIRMWARE_UPDATE=OFF
        - -DDEVELOPER_MODE=ON
        - -DFACTORY_MODE=OFF
        - -DBYOC_MODE=OFF
        - -DTARGET_CONFIG_ROOT=${SNAPCRAFT_PART_SRC}/config
      override-build: |
        snapcraftctl build
        install bin/edge-core ${SNAPCRAFT_PART_INSTALL}
      prime: [edge-core]
    files:
        plugin: dump
        source: files/
    devicejs:
      plugin: nodejs-improved
      nodejs-package-manager: npm
      build-packages:
        - python
        - build-essential
      source: https://github.com/mray190/devicejs-ng.git 
      source-branch: master
      stage: [ -deps/*, -bin/devicedb ]
    devicedb:
      plugin: go
      source: git@github.com:armPelionEdge/devicedb.git
      source-branch: master
      go-importpath: devicedb
