name: pelion-edge
base: core
version: "1.2"
summary: Pelion Edge
description: Pelion Edge
confinement: strict
grade: devel
architectures: 
  - amd64

# List of applications (commands, binaries, daemons) in the snap.
apps:
    edge-core:
      command: launch-edge-core.sh
      daemon: simple
      plugs: [network-bind]
    edge-core-reset-storage:
      command: launch-edge-core.sh --reset-storage
      plugs: [network-bind]
    help:
      command: cat ${SNAP}/help.md
    deviceoswd:
      command: wigwag/system/bin/deviceOSWD -w 3000 -m 900 -s /var/lib/pelion/deviceOSkeepalive
      daemon: simple 
      plugs: [network-bind]
layout:
    /var/lib/edge-core:
        bind: $SNAP_DATA/var/lib/edge-core
    /var/lib/pelion:
        bind: $SNAP_DATA/var/lib/pelion
parts:
    edge-core:
      plugin: cmake
      source: https://github.com/ARMmbed/mbed-edge.git
      source-tag: 0.9.0
      build-packages:
        - build-essential
        - cmake
        - git
      override-pull: | 
        snapcraftctl pull
        git submodule update --init --recursive
        cp ${SNAPCRAFT_PROJECT_DIR}/mbed_cloud_dev_credentials.c config/mbed_cloud_dev_credentials.c
        cp ${SNAPCRAFT_PROJECT_DIR}/cmake/target.cmake config/target.cmake
        cp ${SNAPCRAFT_PART_SRC}/cmake/toolchains/mcc-linux-x86.cmake config/toolchain.cmake
      configflags:
        - -DCMAKE_BUILD_TYPE=Release
        - -DTRACE_LEVEL=INFO
        - -DFIRMWARE_UPDATE=OFF
        - -DDEVELOPER_MODE=ON
        - -DFACTORY_MODE=OFF
        - -DBYOC_MODE=OFF
        - -DTARGET_CONFIG_ROOT=${SNAPCRAFT_PART_SRC}/config
      override-build: |
        snapcraftctl build
        install bin/edge-core ${SNAPCRAFT_PART_INSTALL}
      organize:
        'edge-core': wigwag/mbed/
    files:
        plugin: dump
        source: files/
    devicejs-ng:
      plugin: nodejs-improved
      nodejs-package-manager: npm
      build-packages:
        - python
        - build-essential
      source: git@github.com:armPelionEdge/devicejs-ng.git
      source-branch: master
      stage: [ -deps/*, -bin/devicedb ]
      organize:
        '*': wigwag/devicejs-ng/
    devicedb:
      plugin: go
      source: git@github.com:armPelionEdge/devicedb.git
      source-branch: master
      go-importpath: devicedb
      organize:
        'bin/*': wigwag/system/bin/
    edge-node-modules:
      plugin: nodejs-improved
      nodejs-package-manager: npm
      build-packages:
        - python
        - build-essential
      source: git@github.com:armPelionEdge/edge-node-modules.git
      source-branch: master
      override-build: |
        git am ${SNAPCRAFT_PROJECT_DIR}/patches/edge-node-modules/0001-Added-package.json.patch
        snapcraftctl build
      organize:
        'DevStateManager/': wigwag/wigwag-core-modules/DevStateManager/
        'LEDController/': wigwag/wigwag-core-modules/LEDController/
        'RelayStatsSender/': wigwag/wigwag-core-modules/RelayStatsSender/
        'VirtualDeviceDriver/': wigwag/wigwag-core-modules/VirtualDeviceDriver/
        'onsite-enterprise-server/': wigwag/wigwag-core-modules/onsite-enterprise-server/
        'relay-term/': wigwag/wigwag-core-modules/relay-term/
        'rsmi/': wigwag/devicejs-core-modules/rsmi/
        'zigbeeHA/': wigwag/devicejs-core-modules/zigbeeHA/
        'node_modules/': wigwag/devicejs-core-modules/node_modules/
        'maestroRunner/': wigwag/devicejs-core-modules/maestroRunner/
        'core-interfaces/': wigwag/devicejs-core-modules/core-interfaces/
    deviceoswd:
      plugin: autotools
      source: git@github.com:armPelionEdge/edgeos-wd.git 
      source-branch: master
      build-packages:
        - libtool
        - m4
      override-build: |
        cd deps
        ./install-deps.sh
        cd ..
        make clean
        make deviceOSWD-dummy
        install deviceOSWD ${SNAPCRAFT_PART_INSTALL}/deviceOSWD_dummy
        install deviceOSWD ${SNAPCRAFT_PART_INSTALL}/deviceOSWD
        make clean
        make deviceOSWD-dummy-debug
        install deviceOSWD ${SNAPCRAFT_PART_INSTALL}/deviceOSWD_dummy_debug
        make clean
        make deviceOSWD-a10-debug
        install deviceOSWD ${SNAPCRAFT_PART_INSTALL}/deviceOSWD_a10_debug
        make clean
        make deviceOSWD-a10
        make clean
        make deviceOSWD-a10-relay
        install deviceOSWD ${SNAPCRAFT_PART_INSTALL}/deviceOSWD_a10_relay
        make clean
        make deviceOSWD-a10-tiny841
        install deviceOSWD ${SNAPCRAFT_PART_INSTALL}/deviceOSWD_a10_tiny841
        make clean
        make deviceOSWD-rpi-3bplus
        install deviceOSWD ${SNAPCRAFT_PART_INSTALL}/deviceOSWD_rpi_3bplus
      organize:
        deviceOSWD: wigwag/system/bin/deviceOSWD
        deviceOSWD_dummy: wigwag/system/bin/deviceOSWD_dummy
        deviceOSWD_a10_debug: wigwag/system/bin/deviceOSWD_a10_debug
        deviceOSWD_a10_relay: wigwag/system/bin/deviceOSWD_a10_relay
        deviceOSWD_dummy_debug: wigwag/system/bin/deviceOSWD_dummy_debug
        deviceOSWD_a10_tiny841: wigwag/system/bin/deviceOSWD_a10_tiny841
