#!/bin/bash

if [ ! -f "$SNAP_DATA/edge-core.conf" ]; then
    cp "$SNAP/edge-core.conf" "$SNAP_DATA/edge-core.conf"
fi

if [ ! -f "$SNAP_DATA/fp-edge.conf.json" ]; then
    cp "$SNAP/fp-edge.conf.json" "$SNAP_DATA/fp-edge.conf.json"
fi

if [ ! -d "$SNAP_DATA/userdata/etc" ]; then
    mkdir -p $SNAP_DATA/userdata/etc
fi

if [ ! -d "$SNAP_DATA/localdata" ]; then
    mkdir -p $SNAP_DATA/localdata
fi

if [ ! -d "$SNAP_DATA/wigwag/log" ]; then
    mkdir -p $SNAP_DATA/wigwag/log
fi

if [ ! -d "$SNAP_DATA/upgrades" ]; then
    mkdir -p $SNAP_DATA/upgrades
fi

# copy the config file from $SNAP into $SNAP_COMMON if it doesn't exist
if [ ! -f "$SNAP_DATA/config/daemon.json" ]; then
    mkdir -p "$SNAP_DATA/config"
    cp "$SNAP/config/daemon.json" "$SNAP_DATA/config/daemon.json"
fi

# ensure the layouts dir for /etc/docker exists
mkdir -p "$SNAP_DATA/etc/docker"

if [ ! -f "$SNAP_DATA/maestro-config.yaml" ]; then
    cp "$SNAP/wigwag/wwrelay-utils/conf/maestro-conf/edge-config-dell5000-demo.yaml" "$SNAP_DATA/maestro-config.yaml"
fi

if [ ! -f "$SNAP_DATA/etc/platform_version" ]; then
    mkdir -p "$SNAP_DATA/etc"
    cp "$SNAP/platform_version" "$SNAP_DATA/etc/"
fi

# disable auto-start on some services.
# as of snapcraft v3.8, services can't be configured to be disabled by default
# in snapcraft.yaml and must instead be disabled in the install hook.
snapctl stop --disable pelion-edge.edge-core-reset-storage
