#!/bin/bash
# ----------------------------------------------------------------------------
# Copyright (c) 2020, Arm Limited and affiliates.
#
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ----------------------------------------------------------------------------

if [ ! -f "$SNAP_DATA/edge-core.conf" ]; then
    cp "$SNAP/edge-core.conf" "$SNAP_DATA/edge-core.conf"
fi

if [ ! -f "$SNAP_DATA/edge-proxy.conf.json" ]; then
    cp "$SNAP/edge-proxy.conf.json" "$SNAP_DATA/edge-proxy.conf.json"
fi

if [ ! -d "$SNAP_DATA/userdata/etc" ]; then
    mkdir -p $SNAP_DATA/userdata/etc
fi

if [ ! -d "$SNAP_DATA/localdata" ]; then
    mkdir -p $SNAP_DATA/localdata
fi

if [ ! -d "$SNAP_DATA/wigwag/log" ]; then
    mkdir -p $SNAP_DATA/wigwag/log
fi

if [ ! -d "$SNAP_DATA/upgrades" ]; then
    mkdir -p $SNAP_DATA/upgrades
fi

# copy the config file from $SNAP into $SNAP_COMMON if it doesn't exist
if [ ! -f "$SNAP_DATA/config/daemon.json" ]; then
    mkdir -p "$SNAP_DATA/config"
    cp "$SNAP/config/daemon.json" "$SNAP_DATA/config/daemon.json"
fi

# ensure the layouts dir for /etc/docker exists
mkdir -p "$SNAP_DATA/etc/docker"

if [ ! -f "$SNAP_DATA/maestro-config.yaml" ]; then
    cp "$SNAP/wigwag/wwrelay-utils/conf/maestro-conf/edge-config-dell5000-demo.yaml" "$SNAP_DATA/maestro-config.yaml"
fi

# disable auto-start on some services.
# as of snapcraft v3.8, services can't be configured to be disabled by default
# in snapcraft.yaml and must instead be disabled in the install hook.
